# Les requetes sont placer dans l'ordre logique d'exécution
# rest_client.http sauvegarde les cookies dans un fichier temporaire et les envoie avec chaque requete.
# La route sign-up te login automatiquement!

### Get /api/auth/sign-up/email
POST http://localhost:3000/api/auth/sign-up/email
Content-Type: application/json
Origin: http://localhost:3000

{
  "name": "Eddine",
  "email": "eddine@example.com",
  "password": "secret_password"
}

### Get /api/auth/sign-out
POST http://localhost:3000/api/auth/sign-out
Content-Type: application/json
Origin: http://localhost:3000

### Get /api/auth/sign-in/email
POST http://localhost:3000/api/auth/sign-in/email
Content-Type: application/json
Origin: http://localhost:3000

{
  "email": "eddine@example.com",
  "password": "secret_password"
}

### Post /chats
POST http://localhost:3000/chats
Content-Type: application/json
Origin: http://localhost:3000

{
  "title": "Nouveau Chat"
}

### Get /chats
GET http://localhost:3000/chats

### Get /chats/:id (Ajoute le id du chat)
GET http://localhost:3000/chats/******

### Delete /chats/:id
DELETE http://localhost:3000/chats/******

### Post /messages
POST http://localhost:3000/messages
Content-Type: application/json
# Ajoute le id du chat dans le body 
{
  "input": "Can you write me an essay about AI ?",
  "chatId": "*****",
  "modelName": "gpt-4.1-nano"
}

### Post /webhooks/stripe
POST http://localhost:3000/webhooks/stripe
Content-Type: application/json
# Ajoute ton ID dans le body
{
  "metadata": {
    "userId": "********",
    "tokenAmount": "10000"
  }
}

### Get /me
GET http://localhost:3000/me

### Get /token-usages
GET http://localhost:3000/token-usages